name: Deploy via Rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Copy to server
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --exclude='.git/' --exclude='.github/'

          path: ./

          remote_host: ${{ secrets.DO_HOST }}
          remote_user: ${{ secrets.DO_USER }}
          remote_key: ${{ secrets.DO_SSH_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_port: ${{ secrets.REMOTE_PORT }}
